### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 144: invalid start byte 

### ISSUE THREAD

**Issue by ykkoykko** [FinanceData/FinanceDataReader#197]
Quick Start 코드를 카피 하여 실행 하였는데, 

 KRX 전종목 목록 (설명 중심, 주식+펀드등 전종목)
stocks = fdr.StockListing('KRX-DESC') # 한국거래소: 7,632 종목

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 144: invalid start byte 에러가 발생 합니다.

실행 환경은 다음과 같습니다.
Flask==2.3.3
finance-datareader==0.9.66
html5lib==1.1

전체 에러 메시지는 아래와 같습니다.
Traceback (most recent call last):
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ykko/DBB3_0/website/views/utility_views.py", line 64, in gf_quick_start
    result = Gf_quick_start()
  File "/home/ykko/DBB3_0/website/test/google_finance.py", line 102, in Gf_quick_start
    stocks = fdr.StockListing('KRX-DESC') # 한국거래소: 7,632 종목
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/FinanceDataReader/data.py", line 139, in StockListing
    return KrxStockListing(market).read()
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/FinanceDataReader/krx/listing.py", line 65, in read
    df_listing = pd.read_html(url, header=0)[0]
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/pandas/io/html.py", line 1245, in read_html
    return _parse(
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/pandas/io/html.py", line 1008, in _parse
    raise retained
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/pandas/io/html.py", line 988, in _parse
    tables = p.parse_tables()
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/pandas/io/html.py", line 248, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/pandas/io/html.py", line 658, in _build_doc
    bdoc = self._setup_build_doc()
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/pandas/io/html.py", line 650, in _setup_build_doc
    raw_text = _read(self.io, self.encoding, self.storage_options)
  File "/home/ykko/DBB3_0/env/lib/python3.10/site-packages/pandas/io/html.py", line 145, in _read
    text = handles.handle.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 144: invalid start byte

**Comment by basakpie** [comment]
utf-8 default 인 경우 KRX 호출시에도 encoding 한글 문제로 결과 값이 이전과 다른게 상이하게 응답 되는 것 같습니다.
- df_krx = fdr.StockListing('KRX')

![스크린샷 2024-01-19 오전 12 07 07](https://github.com/FinanceData/FinanceDataReader/assets/20941182/08dbd59d-8da9-4d6b-a784-a3baf82cab48)

**Comment by FinanceData** [comment]
재현이 어렵습니다. 

`FinanceDataReader`만으로 현재 아래와 같이 잘 동작합니다.

![image](https://github.com/FinanceData/FinanceDataReader/assets/806717/ce3aa1a3-9c95-4024-8e1b-e3e78141b0ce)

![image](https://github.com/FinanceData/FinanceDataReader/assets/806717/c4960668-beb7-4018-97a6-6b2c69e73750)

UnicodeDecodeError는 사용하시는 설정 혹은 환경(flask등)에 의해 발생하는 듯 합니다.

내용상의 차이는 인코딩의 문제는 아니며, 'KRX'와 'KRX-DESC' 두가지로 나누어 용도에 따라 사용하도록 의미를 분리하였습니다. 
```
fdr.StockListing('KRX') # 상장종목 전체 리스팅 (가격정보)
fdr.StockListing('KRX-DESC') # 상장종목 부가적인 정보
```

참고하시기 바랍니다.

**Comment by basakpie** [comment]
> 의 차이는 인코딩의 문제는 아니며, 'KRX'와 'KRX-DESC' 두가지로 나누어 용도에 따라 사용하도록 의미를 분리하였습니다.
> 
> ```
> fdr.StockListing('KRX') # 상장종목 전체 리스팅 (가격정보)
> fdr.StockListing('KRX-DESC') # 상장종목 부가적인 정보
> ```

https://github.com/FinanceData/FinanceDataReader/blob/23468361616e4713d470f4dd70d833f42a289f21/krx/listing.py#L66

한가지 더 궁금한게 있어서 문의 드립니다. KRX, KRX-DESC 열 name 이 동일해야 될 것 같은데.. 서로 상이한게 맞는 걸까요?

![스크린샷 2024-01-19 오후 9 26 51](https://github.com/FinanceData/FinanceDataReader/assets/20941182/862fc885-1381-48f1-b8d8-78b3f294d1bc)

![스크린샷 2024-01-19 오후 9 26 57](https://github.com/FinanceData/FinanceDataReader/assets/20941182/5adc7cc6-e049-4176-8a30-05e7ace263a5)

**Comment by basakpie** [comment]
제가 파이썬을 잘 몰라서 우선은 listing.py 파일에 encoding 옵션 넣고 실행해서 UnicodeDecodeError: 'utf-8'  문제를 해소 하였습니다.
OS en_us UTF-8 인 경우 이슈가 될까요?
-  df_listing = pd.read_html(url, header=0, encoding='cp949')[0]

**Comment by ykkoykko** [comment]
fdr.StockListing('KRX-DESC') 는 KrxStockListing(market).read() 를 함수 call  하고,
fdr.StockListing('KRX') 는 KrxMarcapListing(market).read() 를 함수 call 하는 것으로 보이고, 
KrxStockListing(market).read() 에서는 url = 'http://data.krx.co.kr/comm/bldAttendant/executeForResourceBundle.cmd?baseName=krx.mdc.i18n.component&key=B128.bld' 에서 html을 읽어 오고,
KrxMarcapListing(market).read() 는 url = 'http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=13' 에서 html을 읽어 오고 있어서 해당 웹페이지의 encoding을 확인 했더니, 
Page Encoding: ascii, Page Encoding: euc-kr 로 다르게 나오고, euc-kr 은 문제가 없느데, ascii로 되어 있는 웹페이지에서 encoding error가 나옵니다. flask 에서는 utf-8을 사용하고 있습니다. 

사용하는 환경에 따라 encoding문제를 일으 킬 수 있어 보이므로, encoding option을 처리 하도록 하는 것이 좋아 보입니다.

엔코딩 확인 한 코드는 다음과 같습니다.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
import requests
from bs4 import BeautifulSoup
import pandas as pd


def check_url_encoding(url):
    # URL에서 HTML을 가져옵니다.
    response = requests.get(url)
    html = response.content

    # BeautifulSoup을 사용하여 HTML을 파싱합니다.
    soup = BeautifulSoup(html, 'html.parser')

    # 페이지의 인코딩을 확인합니다.
    encoding = soup.original_encoding

    print(f"Page Encoding: {encoding}")


#    stocks2 = fdr.StockListing('KRX-DESC') # 한국거래소: 7,632 종목
#    elif market in ['KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC']:
#        return KrxStockListing(market).read()
url = 'http://data.krx.co.kr/comm/bldAttendant/executeForResourceBundle.cmd?baseName=krx.mdc.i18n.component&key=B128.bld'
check_url_encoding(url)

#    stocks1 = fdr.StockListing('KRX') # KONEX: 126 종목
#    if market in ['KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP']:
#        return KrxMarcapListing(market).read()
url = 'http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=13'
check_url_encoding(url)

**Comment by FinanceData** [comment]
다음 내용들에 대해 인코딩 이슈 FIX 하였습니다

```python
stocks = fdr.StockListing('KRX') # KRX 상장종목 전체
stocks = fdr.StockListing('KRX-DESC') # KRX 종목 상세
stocks = fdr.StockListing('KRX-DELISTING') # 3천+ 종목 - 상장폐지 종목 전체
stocks = fdr.StockListing('KRX-ADMIN') # 50+ 종목 - KRX 관리종목
```
