### ISSUE TITLE
investing.com 자료 가져오는데 문제가 있나요?

### ISSUE THREAD

**Issue by godus1201** [FinanceData/FinanceDataReader#201]
국고채수익율을 가져오지 못합니다
(KR1YT=RR, KR10YT=RR, ...)

>>> df = fdr.DataReader('KR10YT=RR')
HTTP Error 404: Not Found  - symbol "KR10YT=RR" not found or invalid periods
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  **File "C:\Users\SHBY\Anaconda3\envs\py310_64\lib\site-packages\FinanceDataReader\data.py", line 85, in DataReader
    return YahooDailyReader(codes, start, end).read()
  File "C:\Users\SHBY\Anaconda3\envs\py310_64\lib\site-packages\FinanceDataReader\yahoo\data.py", line 58, in read
    return _yahoo_data_reader(self.symbol, self.exchange, self.start, self.end)**
  File "C:\Users\SHBY\Anaconda3\envs\py310_64\lib\site-packages\FinanceDataReader\yahoo\data.py", line 42, in _yahoo_data_reader
    df = df[['Open', 'High', 'Low', 'Adj Close', 'Volume']]
  File "C:\Users\SHBY\Anaconda3\envs\py310_64\lib\site-packages\pandas\core\frame.py", line 3511, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\Users\SHBY\Anaconda3\envs\py310_64\lib\site-packages\pandas\core\indexes\base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\SHBY\Anaconda3\envs\py310_64\lib\site-packages\pandas\core\indexes\base.py", line 5842, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Open', 'High', 'Low', 'Adj Close', 'Volume'], dtype='object')] are in the [columns]"

main data.py 를 열어보니
investing.com 자료는 아예 안가져오도록 되어 있는것 같은데 맞나요??

**Comment by FinanceData** [comment]
현재는 채권 수익률은 yahoo finance에서 데이터를 가져오고 있으며,
미국 국채 수익률(`US5YT`, `US10YT`, `US30YT`)과 FRED의 미국국채데이터(`FRED:DGS1`, `FRED:DGS2`, `FRED:DGS5` ... `FRED:DGS30`)만 지원하고 있습니다.

한국 국채 수익률 데이터는 제공하고 있지 못하고 있습니다.

조만간 한국거래소(KRX)의 채권수익률 데이터를 지원할 예정이며, 업데이트가 이루어지면 답글을 하도록 하겠습니다.

**Comment by ju-ing** [comment]
Investing 모듈을 직접 불러와서 짜는 방식으로 우회하실 수 있습니다.

```
from datetime import datetime, timedelta
from FinanceDataReader.investing.data import InvestingDailyReader

end = datetime.now().strftime("%Y-%m-%d")
start = (datetime.now() - timedelta(20)).strftime("%Y-%m-%d")

reader = InvestingDailyReader(symbol="KR1YT=RR", start=start, end=end)
data = reader.read()
data
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Close</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Volume</th>
      <th>Change</th>
    </tr>
    <tr>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2024-01-19</th>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-01-20</th>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-01-21</th>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-01-22</th>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-01-23</th>
      <td>3.297</td>
      <td>3.300</td>
      <td>3.300</td>
      <td>3.297</td>
      <td>0.0</td>
      <td>-0.0009</td>
    </tr>
    <tr>
      <th>2024-01-24</th>
      <td>3.297</td>
      <td>3.297</td>
      <td>3.300</td>
      <td>3.297</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-01-25</th>
      <td>3.296</td>
      <td>3.297</td>
      <td>3.300</td>
      <td>3.296</td>
      <td>0.0</td>
      <td>-0.0003</td>
    </tr>
    <tr>
      <th>2024-01-26</th>
      <td>3.303</td>
      <td>3.296</td>
      <td>3.303</td>
      <td>3.296</td>
      <td>0.0</td>
      <td>0.0021</td>
    </tr>
    <tr>
      <th>2024-01-29</th>
      <td>3.316</td>
      <td>3.315</td>
      <td>3.316</td>
      <td>3.315</td>
      <td>0.0</td>
      <td>0.0039</td>
    </tr>
    <tr>
      <th>2024-01-30</th>
      <td>3.310</td>
      <td>3.310</td>
      <td>3.311</td>
      <td>3.310</td>
      <td>0.0</td>
      <td>-0.0018</td>
    </tr>
    <tr>
      <th>2024-01-31</th>
      <td>3.308</td>
      <td>3.310</td>
      <td>3.310</td>
      <td>3.308</td>
      <td>0.0</td>
      <td>-0.0006</td>
    </tr>
    <tr>
      <th>2024-02-01</th>
      <td>3.322</td>
      <td>3.308</td>
      <td>3.330</td>
      <td>3.308</td>
      <td>0.0</td>
      <td>0.0042</td>
    </tr>
    <tr>
      <th>2024-02-02</th>
      <td>3.313</td>
      <td>3.322</td>
      <td>3.322</td>
      <td>3.310</td>
      <td>0.0</td>
      <td>-0.0027</td>
    </tr>
    <tr>
      <th>2024-02-03</th>
      <td>3.313</td>
      <td>3.313</td>
      <td>3.313</td>
      <td>3.313</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-02-04</th>
      <td>3.313</td>
      <td>3.313</td>
      <td>3.313</td>
      <td>3.313</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-02-05</th>
      <td>3.313</td>
      <td>3.313</td>
      <td>3.313</td>
      <td>3.313</td>
      <td>0.0</td>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>2024-02-06</th>
      <td>3.355</td>
      <td>3.343</td>
      <td>3.355</td>
      <td>3.343</td>
      <td>0.0</td>
      <td>0.0127</td>
    </tr>
    <tr>
      <th>2024-02-07</th>
      <td>3.377</td>
      <td>3.355</td>
      <td>3.378</td>
      <td>3.355</td>
      <td>0.0</td>
      <td>0.0066</td>
    </tr>
    <tr>
      <th>2024-02-08</th>
      <td>3.403</td>
      <td>3.377</td>
      <td>3.406</td>
      <td>3.377</td>
      <td>0.0</td>
      <td>0.0077</td>
    </tr>
  </tbody>
</table>

**Comment by FinanceData** [comment]
@ju-ing 님께서 놀라운 사용법을 알려주셨습니다. Colab에서 실행하는 경우 @ju-ing 님께서 알려주신 바와 같이 수행이 됩니다.

#166 등의 이슈 처럼 cloudflare 의 정책 문제로 클라이언트 IP에 따라 investing에서 크롤링이 불가합니다. (이 때문에 크롤링 대상을 yahoo로 변경하였습니다). 로컬PC (대한민국 국내 IP)의 경우 아래와 같은 페이지가 반환됩니다.

![image](https://github.com/FinanceData/FinanceDataReader/assets/806717/b5def669-a2d1-46ef-a6c3-c79e64479986)

**Comment by FinanceData** [comment]
다음과 같이 "INVESTING:" 을 명시하여 사용해보세요. 

```python
In [32]: fdr.DataReader('INVESTING:KR10YT=RR')
Out[32]:
            Close   Open   High    Low  Volume  Change
Date
2000-10-26  8.300  8.300  8.300  8.300     0.0 -0.0060
2000-10-27  8.240  8.240  8.240  8.240     0.0 -0.0072
2000-10-28  8.240  8.240  8.240  8.240     0.0  0.0000
2000-10-30  8.220  8.220  8.220  8.220     0.0 -0.0024
2000-11-01  8.150  8.150  8.150  8.150     0.0 -0.0085
...           ...    ...    ...    ...     ...     ...
2020-05-11  1.461  1.433  1.461  1.433     0.0  0.0253
2020-05-12  1.422  1.460  1.460  1.416     0.0 -0.0267
2020-05-13  1.392  1.404  1.412  1.376     0.0 -0.0211
2020-05-14  1.382  1.384  1.404  1.367     0.0 -0.0072
2020-05-15  1.384  1.394  1.397  1.377     0.0  0.0014

[4999 rows x 6 columns]

In [33]: fdr.DataReader('INVESTING:KR1YT=RR')
Out[33]:
             Close    Open    High     Low  Volume  Change
Date
1995-05-03  14.550  14.550  14.550  14.550     0.0  0.0069
1995-05-04  14.550  14.550  14.550  14.550     0.0  0.0000
1995-05-06  14.500  14.500  14.500  14.500     0.0 -0.0034
1995-05-08  14.500  14.500  14.500  14.500     0.0  0.0000
1995-05-09  14.500  14.500  14.500  14.500     0.0  0.0000
...            ...     ...     ...     ...     ...     ...
2016-12-08   1.538   1.535   1.538   1.535     0.0 -0.0077
2016-12-10   1.581   1.581   1.581   1.581     0.0  0.0280
2016-12-12   1.578   1.578   1.578   1.578     0.0 -0.0019
2016-12-13   1.567   1.567   1.567   1.567     0.0 -0.0070
2016-12-14   1.545   1.545   1.545   1.545     0.0 -0.0140

[4999 rows x 6 columns]

In [34]:
```

PS.
INVESTING 을 공식 지원하는 것은 아니지만 FinanceDataReader 에는 cloudflare 우회가 적용되어 있으며 데이터소스를 지정하면 현재 사용가능합니다.

**Comment by ju-ing** [comment]
저는 1월 28일자부터 다시 cloudflare 에 걸렸네요.. 우회 방법을 찾고있습니다.
