### ISSUE TITLE
DataReader KeyError

### ISSUE THREAD

**Issue by hcw1208** [FinanceData/FinanceDataReader#54]
US ETF 전체(1000개) 가격을 불러오는데 KeyError가 발생합니다.
_symbol_list에 10개 ETF ticker 만 넣어 실행해보면 Error없이 종가 정보를 잘 받아왔습니다.
df_price = [fdr.DataReader(ticker, start)['Close'] for ticker in _symbol_list]

Traceback (most recent call last):
  File "C:\Users\LG\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Close'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "api_test.py", line 290, in <module>

  File "api_test.py", line 65, in get_multi_price
    df_price = [fdr.DataReader(ticker, start)['Close'] for ticker in _symbol_list]
  File "api_test.py", line 65, in <listcomp>
    df_price = [fdr.DataReader(ticker, start)['Close'] for ticker in _symbol_list]
  File "C:\Users\LG\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\LG\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'Close'

사용 Version:
(base) PS C:\Users\LG> pip show pandas
Name: pandas
Version: 1.1.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: c:\users\lg\anaconda3\lib\site-packages
Requires: numpy, python-dateutil, pytz
Required-by: statsmodels, seaborn, pandas-datareader, finance-datareader, dart-fss, cufflinks
(base) PS C:\Users\LG> pip show finance-datareader
Name: finance-datareader
Version: 0.9.10
Summary: Financial data reader (price, stock list of markets)
Home-page: https://github.com/financedata/financedatareader
Author: FinanceData.KR
Author-email: plusjune@financedata.kr
License: MIT License
Location: c:\users\lg\anaconda3\lib\site-packages
Requires: tqdm, requests, pandas, lxml, requests-file
Required-by:

**Comment by FinanceData** [comment]
주신 내용만으로 보았을 때 df_price가 DataFrame이 아니라 fdr.DataReader(ticker, start)['Close'] 즉 Series의 list인 듯 합니다.
만일 그렇게 접근하셨다면 Close라는 key가 없는 것이 맞을 듯 합니다.

실제 에러가 발생한 부분의 코드를 알려주시면 더 도움이 될듯 합니다.

(필요하시다면 이 이슈를 다시 열어서 진행해 주셔도 되겠습니다)
